package nginx

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"text/template"

	"cdn-platform/internal/domain"
)

type SiteConfig struct {
	Site domain.Site
}

const (
	defaultCacheMaxSize                 = "5g"
	defaultClientKeepaliveTimeout       = "300s"
	defaultClientKeepaliveRequests      = 1000
	defaultUpstreamConnectTimeout       = "10s"
	defaultUpstreamKeepaliveConnections = 30
	staticAssetPathPattern              = `\.(?:css|js|mjs|map|wasm|woff|woff2|ttf|otf|eot|jpg|jpeg|png|apng|gif|webp|avif|svg|ico|bmp|tif|tiff|webmanifest)$`
)

const configTemplate = `# Generated by cdn-edge-agent. Do not edit.
{{.SecurityConfig}}
{{if .Sites}}
map $http_authorization $cdn_has_auth { default 1; "" 0; }
map $http_cookie $cdn_has_cookie { default 1; "" 0; }
map $uri $cdn_is_static_asset { default 0; ~*{{.StaticAssetPathPattern}} 1; }
map "$cdn_is_static_asset:$cdn_has_cookie" $cdn_cookie_cache_bypass { default 0; "0:1" 1; }
map "$cdn_is_static_asset:$cdn_has_auth" $cdn_upstream_cookie { default $http_cookie; "1:0" ""; }
map $http_upgrade $cdn_is_websocket { default 0; ~*^websocket$ 1; }
map $cdn_is_websocket $cdn_connection_upgrade { default ""; 1 upgrade; }
map $cdn_is_websocket $cdn_upstream_upgrade { default ""; 1 $http_upgrade; }
map $http_accept $cdn_accepts_event_stream { default 0; ~*text/event-stream 1; }
map $http_x_cdn_stream $cdn_forced_stream { default 0; "1" 1; }
map "$request_method:$cdn_is_websocket:$cdn_accepts_event_stream:$cdn_forced_stream" $cdn_auto_stream {
    default 0;
    ~^POST: 1;
    ~^[^:]+:1: 1;
    ~^[^:]+:[01]:1: 1;
    ~^[^:]+:[01]:[01]:1$ 1;
}

proxy_cache_path /opt/cdn-edge/cache levels=1:2 keys_zone=cdn_cache:100m inactive=7d max_size={{.CacheMaxSize}} use_temp_path=off;
log_format cdn_json escape=json '{"timestamp":"$time_iso8601","site_id":"$cdn_site_id","client_ip":"$remote_addr","method":"$request_method","path":"$uri","status":$status,"bytes":$body_bytes_sent,"duration_seconds":$request_time,"upstream":"$upstream_addr","cache_status":"$upstream_cache_status"}';
{{end}}

{{if .DefaultHTTP}}server {
    listen 80 default_server;
    server_name _;
{{if .SecurityEnabled}}    access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
{{end}}
    location = /__cdn_health { access_log off; add_header Content-Type text/plain; return 200 "ok\n"; }
    location / { return 404; }
}
{{end}}

{{if .Sites}}
server {
    listen 443 ssl default_server;
    ssl_reject_handshake on;
}
{{end}}

{{range .Sites}}
{{if .BackupHostPort}}
upstream origin_{{.ID}}_primary {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}

upstream origin_{{.ID}}_backup {
    server {{.BackupHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{else}}
upstream origin_{{.ID}} {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{end}}

server {
    listen 80;
    server_name {{.DomainList}};
    {{if $.SecurityEnabled}}access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
    {{end}}
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name {{.DomainList}};
    client_max_body_size {{.ClientMaxBodySizeMB}}m;
    keepalive_timeout {{$.ClientKeepaliveTimeout}};
    keepalive_requests {{$.ClientKeepaliveRequests}};
    {{if $.SecurityEnabled}}access_log /opt/cdn-edge/logs/security.json cdn_security_json if=$cdn_security_policy_id;
    if ($cdn_security_policy_id) { return 444; }
    {{end}}

    ssl_certificate /opt/cdn-edge/config/certs/{{.ID}}.crt;
    ssl_certificate_key /opt/cdn-edge/config/certs/{{.ID}}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TLS:10m;

    set $cdn_site_id "{{.ID}}";
    access_log /opt/cdn-edge/logs/access.json cdn_json;

    location = /__cdn_health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "{{.HealthBody}}\n";
    }

    {{if .GRPC}}
    location / {
        grpc_pass {{.PrimaryScheme}}://origin_{{.ID}}{{if .BackupHostPort}}_primary{{end}};
        grpc_set_header Host {{.HostHeader}};
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        grpc_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        grpc_next_upstream_tries 2;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.PrimaryTLSName}};
        grpc_ssl_verify on;
        grpc_ssl_verify_depth 3;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if .BackupHostPort}}
        grpc_intercept_errors on;
        error_page 500 502 503 504 = @cdn_grpc_backup_{{.ID}};
        {{end}}
    }

    {{if .BackupHostPort}}
    location @cdn_grpc_backup_{{.ID}} {
        internal;
        grpc_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
        grpc_set_header Host {{.BackupHostHeader}};
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.BackupTLSName}};
        grpc_ssl_verify on;
        grpc_ssl_verify_depth 3;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
    }
    {{end}}
	{{else}}
	proxy_http_version 1.1;
	proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
	proxy_next_upstream_tries 2;
	proxy_connect_timeout {{$.UpstreamConnectTimeout}};
	{{if .BackupHostPort}}
	recursive_error_pages on;
	{{end}}
	{{if .CacheEnabled}}
	proxy_cache cdn_cache;
	proxy_cache_key "{{.ID}}:{{.CacheGeneration}}:$scheme$host$request_uri";
    proxy_cache_methods GET HEAD;
    proxy_cache_bypass $cdn_has_auth $cdn_cookie_cache_bypass;
    proxy_no_cache $cdn_has_auth $cdn_cookie_cache_bypass $upstream_http_set_cookie;
    proxy_cache_valid 200 301 302 10m;
    proxy_cache_valid 404 1m;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 10s;
	proxy_cache_revalidate on;
	proxy_cache_background_update on;
	proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
	{{end}}

	location / {
		error_page 418 = @cdn_stream_{{.ID}};
		error_page 419 = @cdn_http_{{.ID}};
		if ($cdn_auto_stream) { return 418; }
		return 419;
	}

	location @cdn_http_{{.ID}} {
		internal;
		proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}{{if .BackupHostPort}}_primary{{end}};
		proxy_set_header Host {{.HostHeader}};
		proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		proxy_set_header X-CDN-Stream "";
		{{if .CacheEnabled}}proxy_set_header Cookie $cdn_upstream_cookie;
		{{end}}
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .AlwaysUnbuffered}}
		proxy_cache off;
		proxy_buffering off;
		proxy_request_buffering off;
		{{end}}
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.PrimaryTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if .BackupHostPort}}
        proxy_intercept_errors on;
		error_page 500 502 503 504 = @cdn_backup_{{.ID}};
		{{end}}
	}

	location @cdn_stream_{{.ID}} {
		internal;
		proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}{{if .BackupHostPort}}_primary{{end}};
		proxy_set_header Host {{.HostHeader}};
		proxy_set_header Upgrade $cdn_upstream_upgrade;
		proxy_set_header Connection $cdn_connection_upgrade;
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if .AlwaysUnbuffered}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		{{end}}
		{{if .UseTLS}}
		proxy_ssl_server_name on;
		proxy_ssl_name {{.PrimaryTLSName}};
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 3;
		proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		{{end}}
		{{if .BackupHostPort}}
		proxy_intercept_errors on;
		error_page 500 502 503 504 = @cdn_stream_backup_{{.ID}};
		{{end}}
	}

	{{if .BackupHostPort}}
	location @cdn_backup_{{.ID}} {
		internal;
		proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
		proxy_set_header Host {{.BackupHostHeader}};
		proxy_set_header Upgrade "";
		proxy_set_header Connection "";
		proxy_set_header X-CDN-Stream "";
		{{if .CacheEnabled}}proxy_set_header Cookie $cdn_upstream_cookie;
		{{end}}
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .AlwaysUnbuffered}}
		proxy_cache off;
		proxy_buffering off;
		proxy_request_buffering off;
		{{end}}
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		{{end}}
	}

	location @cdn_stream_backup_{{.ID}} {
		internal;
		proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
		proxy_set_header Host {{.BackupHostHeader}};
		proxy_set_header Upgrade $cdn_upstream_upgrade;
		proxy_set_header Connection $cdn_connection_upgrade;
		proxy_set_header X-CDN-Stream "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_cache off;
		proxy_buffering off;
		{{if .AlwaysUnbuffered}}
		proxy_request_buffering off;
		{{end}}
		proxy_read_timeout {{.ReadWriteTimeout}};
		proxy_send_timeout {{.ReadWriteTimeout}};
		{{if .Passthrough}}
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupTLSName}};
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
		{{end}}
	}
	{{end}}
	{{end}}
}
{{end}}
`

type renderedSite struct {
	ID                  string
	DomainList          string
	HealthBody          string
	PrimaryHostPort     string
	PrimaryTLSName      string
	PrimaryScheme       string
	UseTLS              bool
	BackupHostPort      string
	BackupTLSName       string
	BackupHostHeader    string
	HostHeader          string
	CacheGeneration     int64
	GRPC                bool
	Passthrough         bool
	ClientMaxBodySizeMB int
	ReadWriteTimeout    string
	CacheEnabled        bool
	AlwaysUnbuffered    bool
}

type renderInput struct {
	Sites                        []renderedSite
	DefaultHTTP                  bool
	SecurityEnabled              bool
	SecurityConfig               string
	CacheMaxSize                 string
	ClientKeepaliveTimeout       string
	ClientKeepaliveRequests      int
	UpstreamConnectTimeout       string
	UpstreamKeepaliveConnections int
	StaticAssetPathPattern       string
}

func Render(sites []domain.Site) (string, error) {
	return RenderWithSecurity(sites, nil)
}

func RenderWithSecurity(sites []domain.Site, securityPolicies []domain.SecurityPolicy) (string, error) {
	items := make([]renderedSite, 0, len(sites))
	dedicatedTCP := false
	for _, site := range sites {
		if site.TCPOnly {
			dedicatedTCP = true
		}
		if !site.Enabled || site.TCPOnly {
			continue
		}
		clientMaxBodySizeMB, err := domain.NormalizeClientMaxBodySizeMB(site.ClientMaxBodySizeMB)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		readWriteTimeoutSeconds, err := domain.NormalizeReadWriteTimeoutSeconds(site.ReadWriteTimeoutSeconds)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		primary, err := parseOrigin(site.PrimaryOrigin)
		if err != nil {
			return "", fmt.Errorf("site %s primary origin: %w", site.Name, err)
		}
		if site.Passthrough && primary.Scheme != "http" && primary.Scheme != "https" {
			return "", fmt.Errorf("site %s passthrough mode is only supported for HTTP and HTTPS origins", site.Name)
		}
		item := renderedSite{
			ID: site.ID, DomainList: strings.Join(site.Domains, " "), HealthBody: SiteHealthBody(site.ID), PrimaryHostPort: primary.Host, PrimaryTLSName: site.PrimaryOrigin.TLSServerName,
			PrimaryScheme: domain.ProxyScheme(primary.Scheme), UseTLS: domain.OriginUsesTLS(primary.Scheme), HostHeader: site.PrimaryOrigin.HostHeader, CacheGeneration: site.CacheGeneration,
			GRPC: domain.IsGRPCScheme(primary.Scheme), Passthrough: site.Passthrough, ClientMaxBodySizeMB: clientMaxBodySizeMB,
			ReadWriteTimeout: fmt.Sprintf("%ds", readWriteTimeoutSeconds),
			CacheEnabled:     primary.Scheme == "http" || primary.Scheme == "https",
			AlwaysUnbuffered: site.Passthrough || domain.IsWebSocketScheme(primary.Scheme),
		}
		item.CacheEnabled = item.CacheEnabled && !site.Passthrough
		if item.HostHeader == "" {
			item.HostHeader = primary.Hostname()
		}
		if item.PrimaryTLSName == "" {
			item.PrimaryTLSName = primary.Hostname()
		}
		if site.BackupOrigin != nil && site.BackupOrigin.Enabled {
			backup, err := parseOrigin(*site.BackupOrigin)
			if err != nil {
				return "", fmt.Errorf("site %s backup origin: %w", site.Name, err)
			}
			if backup.Scheme != primary.Scheme {
				return "", fmt.Errorf("site %s origins must use the same scheme", site.Name)
			}
			item.BackupHostPort = backup.Host
			item.BackupTLSName = site.BackupOrigin.TLSServerName
			item.BackupHostHeader = site.BackupOrigin.HostHeader
			if item.BackupHostHeader == "" {
				item.BackupHostHeader = backup.Hostname()
			}
			if item.BackupTLSName == "" {
				item.BackupTLSName = backup.Hostname()
			}
		}
		items = append(items, item)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	template, err := template.New("nginx").Parse(configTemplate)
	if err != nil {
		return "", err
	}
	var out bytes.Buffer
	if err := template.Execute(&out, renderInput{
		Sites:                        items,
		DefaultHTTP:                  !dedicatedTCP,
		SecurityEnabled:              len(enabledSecurityPolicies(securityPolicies)) > 0 && !dedicatedTCP,
		SecurityConfig:               renderSecurityConfig(securityPolicies, !dedicatedTCP),
		CacheMaxSize:                 defaultCacheMaxSize,
		ClientKeepaliveTimeout:       defaultClientKeepaliveTimeout,
		ClientKeepaliveRequests:      defaultClientKeepaliveRequests,
		UpstreamConnectTimeout:       defaultUpstreamConnectTimeout,
		UpstreamKeepaliveConnections: defaultUpstreamKeepaliveConnections,
		StaticAssetPathPattern:       staticAssetPathPattern,
	}); err != nil {
		return "", err
	}
	return out.String(), nil
}

func enabledSecurityPolicies(policies []domain.SecurityPolicy) []domain.SecurityPolicy {
	result := make([]domain.SecurityPolicy, 0, len(policies))
	for _, policy := range policies {
		if policy.Enabled {
			result = append(result, policy)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].Priority != result[j].Priority {
			return result[i].Priority < result[j].Priority
		}
		return result[i].ID < result[j].ID
	})
	return result
}

func renderSecurityConfig(policies []domain.SecurityPolicy, httpEnabled bool) string {
	if policies == nil {
		return ""
	}
	var result strings.Builder
	result.WriteString(SecurityRevisionMarker(policies))
	result.WriteByte('\n')
	policies = enabledSecurityPolicies(policies)
	if len(policies) == 0 || !httpEnabled {
		return result.String()
	}
	result.WriteString("map $uri $cdn_security_policy_id {\n    default \"\";\n")
	for _, policy := range policies {
		result.WriteString("    ~\"")
		result.WriteString(escapeNginxQuotedPattern(policy.Pattern))
		result.WriteString("\" \"")
		result.WriteString(policy.ID)
		result.WriteString("\";\n")
	}
	result.WriteString("}\n\nmap $cdn_security_policy_id $cdn_security_action {\n    default \"\";\n")
	for _, policy := range policies {
		result.WriteString(fmt.Sprintf("    \"%s\" \"%s\";\n", policy.ID, policy.Action))
	}
	result.WriteString("}\n\nmap $cdn_security_policy_id $cdn_security_ban_seconds {\n    default 0;\n")
	for _, policy := range policies {
		result.WriteString(fmt.Sprintf("    \"%s\" %d;\n", policy.ID, policy.BanDurationSeconds))
	}
	result.WriteString("}\n\nlog_format cdn_security_json escape=json '{\"timestamp\":\"$time_iso8601\",\"policy_id\":\"$cdn_security_policy_id\",\"action\":\"$cdn_security_action\",\"ban_seconds\":$cdn_security_ban_seconds,\"client_ip\":\"$remote_addr\",\"host\":\"$host\",\"method\":\"$request_method\",\"path\":\"$uri\"}';\n")
	return result.String()
}

func SecurityRevisionMarker(policies []domain.SecurityPolicy) string {
	type revisionPolicy struct {
		ID                 string
		Name               string
		Enabled            bool
		Pattern            string
		Action             domain.SecurityPolicyAction
		BanDurationSeconds int
		Priority           int
	}
	ordered := append([]domain.SecurityPolicy(nil), policies...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].ID < ordered[j].ID })
	revision := make([]revisionPolicy, 0, len(ordered))
	for _, policy := range ordered {
		revision = append(revision, revisionPolicy{
			ID: policy.ID, Name: policy.Name, Enabled: policy.Enabled, Pattern: policy.Pattern,
			Action: policy.Action, BanDurationSeconds: policy.BanDurationSeconds, Priority: policy.Priority,
		})
	}
	encoded, _ := json.Marshal(revision)
	digest := sha256.Sum256(encoded)
	return fmt.Sprintf("# CDN security revision: %x", digest[:])
}

func HasSecurityRevision(configuration string, policies []domain.SecurityPolicy) bool {
	return strings.Contains(configuration, SecurityRevisionMarker(policies))
}

func escapeNginxQuotedPattern(pattern string) string {
	pattern = strings.ReplaceAll(pattern, `\`, `\\`)
	return strings.ReplaceAll(pattern, `"`, `\"`)
}

func SiteHealthBody(siteID string) string {
	return "site=" + siteID
}

func HasSiteHealth(configuration, siteID string) bool {
	return strings.Contains(configuration, `return 200 "`+SiteHealthBody(siteID)+`\n";`)
}

func parseOrigin(origin domain.Origin) (*url.URL, error) {
	parsed, err := url.Parse(origin.URL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return nil, fmt.Errorf("must be an absolute URL")
	}
	if !domain.ValidOriginScheme(parsed.Scheme) {
		return nil, fmt.Errorf("scheme must be http, https, ws, wss, grpc, or grpcs")
	}
	if parsed.Path != "" && parsed.Path != "/" {
		return nil, fmt.Errorf("origin URL cannot include a path")
	}
	if parsed.Port() == "" {
		if domain.OriginUsesTLS(parsed.Scheme) {
			parsed.Host += ":443"
		} else {
			parsed.Host += ":80"
		}
	}
	return parsed, nil
}
