package nginx

import (
	"bytes"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"text/template"

	"cdn-platform/internal/domain"
)

type SiteConfig struct {
	Site domain.Site
}

const (
	defaultCacheMaxSize                 = "5g"
	defaultClientKeepaliveTimeout       = "300s"
	defaultClientKeepaliveRequests      = 1000
	defaultUpstreamConnectTimeout       = "10s"
	defaultUpstreamKeepaliveConnections = 30
)

const configTemplate = `# Generated by cdn-edge-agent. Do not edit.
{{if .Sites}}
map $http_authorization $cdn_has_auth { default 1; "" 0; }
map $http_cookie $cdn_has_cookie { default 1; "" 0; }
map $http_upgrade $cdn_connection_upgrade { default upgrade; "" ""; }

proxy_cache_path /opt/cdn-edge/cache levels=1:2 keys_zone=cdn_cache:100m inactive=7d max_size={{.CacheMaxSize}} use_temp_path=off;
log_format cdn_json escape=json '{"timestamp":"$time_iso8601","site_id":"$cdn_site_id","client_ip":"$remote_addr","method":"$request_method","path":"$uri","status":$status,"bytes":$body_bytes_sent,"duration_seconds":$request_time,"upstream":"$upstream_addr","cache_status":"$upstream_cache_status"}';
{{end}}

server {
    listen 80 default_server;
    server_name _;
    location = /__cdn_health { access_log off; add_header Content-Type text/plain; return 200 "ok\n"; }
    location / { return 404; }
}

{{range .Sites}}
{{if .BackupHostPort}}
upstream origin_{{.ID}}_primary {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}

upstream origin_{{.ID}}_backup {
    server {{.BackupHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{else}}
upstream origin_{{.ID}} {
    server {{.PrimaryHostPort}} max_fails=2 fail_timeout=10s;
    keepalive {{$.UpstreamKeepaliveConnections}};
}
{{end}}

server {
    listen 80;
    server_name {{.DomainList}};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name {{.DomainList}};
    client_max_body_size {{.ClientMaxBodySizeMB}}m;
    keepalive_timeout {{$.ClientKeepaliveTimeout}};
    keepalive_requests {{$.ClientKeepaliveRequests}};

    ssl_certificate /opt/cdn-edge/config/certs/{{.ID}}.crt;
    ssl_certificate_key /opt/cdn-edge/config/certs/{{.ID}}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TLS:10m;

    set $cdn_site_id "{{.ID}}";
    access_log /opt/cdn-edge/logs/access.json cdn_json;

    {{if .GRPC}}
    location / {
        grpc_pass {{.PrimaryScheme}}://origin_{{.ID}}{{if .BackupHostPort}}_primary{{end}};
        grpc_set_header Host {{.HostHeader}};
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        grpc_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        grpc_next_upstream_tries 2;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.PrimaryHostname}};
        grpc_ssl_verify on;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if .BackupHostPort}}
        grpc_intercept_errors on;
        error_page 500 502 503 504 = @cdn_grpc_backup_{{.ID}};
        {{end}}
    }

    {{if .BackupHostPort}}
    location @cdn_grpc_backup_{{.ID}} {
        internal;
        grpc_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
        grpc_set_header Host {{.BackupHostHeader}};
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto https;
        grpc_set_header TE trailers;
        grpc_connect_timeout {{$.UpstreamConnectTimeout}};
        grpc_read_timeout 1h;
        grpc_send_timeout 1h;
        {{if .UseTLS}}
        grpc_ssl_server_name on;
        grpc_ssl_name {{.BackupHostname}};
        grpc_ssl_verify on;
        grpc_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
    }
    {{end}}
    {{else}}
    proxy_http_version 1.1;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_next_upstream_tries 2;
    proxy_connect_timeout {{$.UpstreamConnectTimeout}};
    {{if not .Passthrough}}
    proxy_cache cdn_cache;
    proxy_cache_key "{{.ID}}:{{.CacheGeneration}}:$scheme$host$request_uri";
    proxy_cache_methods GET HEAD;
    proxy_cache_bypass $cdn_has_auth $cdn_has_cookie;
    proxy_no_cache $cdn_has_auth $cdn_has_cookie $upstream_http_set_cookie;
    proxy_cache_valid 200 301 302 10m;
    proxy_cache_valid 404 1m;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 10s;
    proxy_cache_revalidate on;
    proxy_cache_background_update on;
    proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
    proxy_read_timeout 60s;
    {{end}}

    {{$site := .}}
    {{range .StreamLocations}}
    location {{.}} {
        proxy_pass {{$site.PrimaryScheme}}://origin_{{$site.ID}}{{if $site.BackupHostPort}}_primary{{end}};
        proxy_http_version 1.1;
        proxy_set_header Host {{$site.HostHeader}};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $cdn_connection_upgrade;
        proxy_cache off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_connect_timeout {{$.UpstreamConnectTimeout}};
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        {{if $site.Passthrough}}
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if $site.UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{$site.PrimaryHostname}};
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if $site.BackupHostPort}}
        proxy_intercept_errors on;
        error_page 500 502 503 504 = @cdn_stream_backup_{{$site.ID}};
        {{end}}
    }
    {{end}}

    {{if not .AllStreaming}}
    location / {
        proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}{{if .BackupHostPort}}_primary{{end}};
        proxy_set_header Host {{.HostHeader}};
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        {{if .Passthrough}}
        proxy_cache off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_connect_timeout {{$.UpstreamConnectTimeout}};
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.PrimaryHostname}};
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
        {{if .BackupHostPort}}
        proxy_intercept_errors on;
        error_page 500 502 503 504 = @cdn_backup_{{.ID}};
        {{end}}
    }
    {{end}}

    {{if .BackupHostPort}}
    {{if not .AllStreaming}}
    location @cdn_backup_{{.ID}} {
        internal;
        proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
        proxy_set_header Host {{.BackupHostHeader}};
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        {{if .Passthrough}}
        proxy_cache off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_connect_timeout {{$.UpstreamConnectTimeout}};
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupHostname}};
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
    }
    {{end}}
    {{if .StreamLocations}}
    location @cdn_stream_backup_{{.ID}} {
        internal;
        proxy_pass {{.PrimaryScheme}}://origin_{{.ID}}_backup;
        proxy_http_version 1.1;
        proxy_set_header Host {{.BackupHostHeader}};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $cdn_connection_upgrade;
        proxy_cache off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_connect_timeout {{$.UpstreamConnectTimeout}};
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        {{if $site.Passthrough}}
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        {{end}}
        {{if .UseTLS}}
        proxy_ssl_server_name on;
        proxy_ssl_name {{.BackupHostname}};
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        {{end}}
    }
    {{end}}
    {{end}}
    {{end}}
}
{{end}}
`

type renderedSite struct {
	ID                  string
	DomainList          string
	PrimaryHostPort     string
	PrimaryHostname     string
	PrimaryScheme       string
	UseTLS              bool
	BackupHostPort      string
	BackupHostname      string
	BackupHostHeader    string
	HostHeader          string
	CacheGeneration     int64
	GRPC                bool
	Passthrough         bool
	ClientMaxBodySizeMB int
	StreamLocations     []string
	AllStreaming        bool
}

type renderInput struct {
	Sites                        []renderedSite
	CacheMaxSize                 string
	ClientKeepaliveTimeout       string
	ClientKeepaliveRequests      int
	UpstreamConnectTimeout       string
	UpstreamKeepaliveConnections int
}

func Render(sites []domain.Site) (string, error) {
	items := make([]renderedSite, 0, len(sites))
	for _, site := range sites {
		if !site.Enabled {
			continue
		}
		clientMaxBodySizeMB, err := domain.NormalizeClientMaxBodySizeMB(site.ClientMaxBodySizeMB)
		if err != nil {
			return "", fmt.Errorf("site %s: %w", site.Name, err)
		}
		primary, err := parseOrigin(site.PrimaryOrigin)
		if err != nil {
			return "", fmt.Errorf("site %s primary origin: %w", site.Name, err)
		}
		if site.Passthrough && primary.Scheme != "http" && primary.Scheme != "https" {
			return "", fmt.Errorf("site %s passthrough mode is only supported for HTTP and HTTPS origins", site.Name)
		}
		item := renderedSite{
			ID: site.ID, DomainList: strings.Join(site.Domains, " "), PrimaryHostPort: primary.Host, PrimaryHostname: primary.Hostname(),
			PrimaryScheme: domain.ProxyScheme(primary.Scheme), UseTLS: domain.OriginUsesTLS(primary.Scheme), HostHeader: site.PrimaryOrigin.HostHeader, CacheGeneration: site.CacheGeneration,
			GRPC: domain.IsGRPCScheme(primary.Scheme), Passthrough: site.Passthrough, ClientMaxBodySizeMB: clientMaxBodySizeMB,
		}
		streamPaths := site.StreamPaths
		if domain.IsWebSocketScheme(primary.Scheme) && len(streamPaths) == 0 {
			streamPaths = []string{"/"}
		}
		for _, path := range streamPaths {
			if path == "/" {
				item.StreamLocations = append(item.StreamLocations, "/")
				item.AllStreaming = true
				continue
			}
			item.StreamLocations = append(item.StreamLocations, "= "+path, "^~ "+path+"/")
		}
		if item.HostHeader == "" {
			item.HostHeader = primary.Hostname()
		}
		if site.BackupOrigin != nil && site.BackupOrigin.Enabled {
			backup, err := parseOrigin(*site.BackupOrigin)
			if err != nil {
				return "", fmt.Errorf("site %s backup origin: %w", site.Name, err)
			}
			if backup.Scheme != primary.Scheme {
				return "", fmt.Errorf("site %s origins must use the same scheme", site.Name)
			}
			item.BackupHostPort = backup.Host
			item.BackupHostname = backup.Hostname()
			item.BackupHostHeader = site.BackupOrigin.HostHeader
			if item.BackupHostHeader == "" {
				item.BackupHostHeader = backup.Hostname()
			}
		}
		items = append(items, item)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	template, err := template.New("nginx").Parse(configTemplate)
	if err != nil {
		return "", err
	}
	var out bytes.Buffer
	if err := template.Execute(&out, renderInput{
		Sites:                        items,
		CacheMaxSize:                 defaultCacheMaxSize,
		ClientKeepaliveTimeout:       defaultClientKeepaliveTimeout,
		ClientKeepaliveRequests:      defaultClientKeepaliveRequests,
		UpstreamConnectTimeout:       defaultUpstreamConnectTimeout,
		UpstreamKeepaliveConnections: defaultUpstreamKeepaliveConnections,
	}); err != nil {
		return "", err
	}
	return out.String(), nil
}

func parseOrigin(origin domain.Origin) (*url.URL, error) {
	parsed, err := url.Parse(origin.URL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return nil, fmt.Errorf("must be an absolute URL")
	}
	if !domain.ValidOriginScheme(parsed.Scheme) {
		return nil, fmt.Errorf("scheme must be http, https, ws, wss, grpc, or grpcs")
	}
	if parsed.Path != "" && parsed.Path != "/" {
		return nil, fmt.Errorf("origin URL cannot include a path")
	}
	if parsed.Port() == "" {
		if domain.OriginUsesTLS(parsed.Scheme) {
			parsed.Host += ":443"
		} else {
			parsed.Host += ":80"
		}
	}
	return parsed, nil
}
